<html>
<head>
	<title>Абстрактная система заказов</title>
	<meta charset="utf-8">

<script> 
	var Viewer = {
		id: <?php echo isset($_SESSION['user_id']) ? $_SESSION['user_id'] : 0?>,
		role: <?php echo isset($_SESSION['role']) ? $_SESSION['role'] : 0?>,
		name: <?php echo isset($_SESSION['name']) ? '"' . $_SESSION['name'] . '"' : '""'?>
	}
</script>
	
	
</head>


<body>

<div id="menu">
</div>

<div id="user"></div>

<div id="content">
	<?//=$content?>
</div>

<script src="/js/libs/require.js" data-main="/js/main.js"></script>

</body>
</html>
